name: car_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.3
  provider: ^6.0.5
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  google_maps_flutter_web: ^0.3.3 
